// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Feel = 1,
  FeelBlock = 2,
  SimpleTextBlock = 3,
  Feelers = 4,
  Insert = 5,
  EmptyInsert = 6,
  ConditionalSpanner = 7,
  ConditionalSpannerClose = 8,
  ConditionalSpannerCloseNl = 9,
  LoopSpanner = 10,
  LoopSpannerClose = 11,
  LoopSpannerCloseNl = 12
