// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {feel, feelBlock, simpleTextBlock} from "./tokens"
import {feelersHighlighting} from "./highlight"
export const parser = LRParser.deserialize({
  version: 14,
  states: "$bOQOXOOOfOTO'#CbOOOW'#Ci'#CiOqOSO'#CcOvOSO'#CdOOOW'#Cl'#ClOOOW'#Ce'#CeO{OXO'#ChO!dOQOOQOOOOOO!iOPO,58{O!nOTO,58|OOOW,58|,58|O!vOPO,58}O!{OPO,59OOOOW-E6c-E6cOOOW1G.g1G.gO#QOPO1G.gOOOW1G.h1G.hO#VOXO1G.iO#hOXO1G.jOOOW7+$R7+$RO#yOPO7+$TO$OOPO7+$UOOOW<<Go<<GoOOOW<<Gp<<Gp",
  stateData: "$T~ORUOZWO^POaROcSOY[P~OQYOZZO_[O~OQ]O~OQ^O~ORUO^POaROcSOY[Xb[Xd[X~OPXO~O_`O~OQaO_bO~O_cO~O_dO~O_eO~ORUO^POaROcSOb[P~ORUO^POaROcSOd[P~ObhO~OdiO~O",
  goto: "!VaPPPPPbbhhnPPv!PPP!PXQOVcdXTOVcdUVOcdR_VQXOQfcRgdXUOVcd",
  nodeNames: "⚠ Feel FeelBlock SimpleTextBlock Feelers Insert EmptyInsert ConditionalSpanner LoopSpanner",
  maxTerm: 20,
  propSources: [feelersHighlighting],
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "$m~RR!_!`[#o#pa#q#r$b~aOZ~~dP#o#pg~lQ^~str!P!Q!{~uQ#]#^{#`#a!^~!OP#Y#Z!R~!UPpq!X~!^Oa~~!aP#c#d!d~!gP#c#d!j~!mP#d#e!p~!sPpq!v~!{Oc~~#OQ#]#^#U#`#a#m~#XP#Y#Z#[~#_P#q#r#b~#eP#q#r#h~#mOb~~#pP#c#d#s~#vP#c#d#y~#|P#d#e$P~$SP#q#r$V~$YP#q#r$]~$bOd~~$eP#q#r$h~$mO_~",
  tokenizers: [0, feel, feelBlock, simpleTextBlock],
  topRules: {"Feelers":[0,4]},
  tokenPrec: 0
})
